### ISSUE TITLE
Addon loader doesn't work in Electron

### ISSUE THREAD

**Issue by ovanschie** [sourcelair/xterm.js#305]
Since the 2.0 release the loadAddon method doesn't work anymore in Electron apps.

Code:
```
var Terminal = require('xterm');
Terminal.loadAddon('fit');
```
Error:
`Uncaught Error: Cannot find module '/src/../addons/fit'`

The same code does work with version 1.1.3.

## Details
- Browser and browser version: Electron 1.4.3 (Chrome 53.0.2785.113)
- OS version: MacOS Sierra
- xterm.js version: 2.0.0 / 2.0.1

**Comment by parisk** [comment]
Hi @ovanschie, thanks for reporting. This should be fixed with #304, though I think we will conclude on a better and more permanent solution for add-ons in the coming release.

Could you please take a look at the `update-addons-paths` branch and let me know if it works for you?

**Comment by ovanschie** [comment]
Thanks for the reply. I tried the `update-addons-paths` branch, but unfortunately it still doesn't work. 

I found that `__dirname` used in the addon loader returns `/src` in v2, in v1 it returns the full path `/<project dir>/node_modules/xterm/src` for some reason. 

Maybe this has something to do with it?

**Comment by Tyriar** [comment]
I saw something like this on the TypeScript branch, this is what I did there to get the tests to work https://github.com/sourcelair/xterm.js/pull/296/files#diff-d4f745d6f29faa0617f2e02bb95f0c44R686

**Comment by parisk** [comment]
@ovanschie I pushed an update, removing `__dirname` as it is redundant (at least).

Also starting from **2.0** you should be importing xterm.js from `dist`, instead of `src`. Are there any chances this was caused by importing from the wrong directory?

@Tyriar the `build` directory should be used only for development as it is ignored by Git. If we load addons from `build` this means that the user will have to build the core manually before using the addons.

**Comment by parisk** [comment]
@ovanschie could you give another try at the `update-addons-paths` and if it still crashes, send us the piece of code that imports xterm.js? It should be just one line.

**Comment by ovanschie** [comment]
@parisk see my first comment for the import code i used. 

The updated code in `update-addons-paths` works for me now!

**Comment by parisk** [comment]
> @parisk see my first comment for the import code i used.

🙈  I totally lost this

> The updated code in update-addons-paths works for me now!

👍  moving forward with merging.
